### PR TITLE
Revert "Revert "Update our clone with upstream updates for Swift warnings""

### PR DESCRIPTION
**Pull request by meiyu2019**
Reverts Calthings/iOS_DFU_Library#4

### CODE REVIEW

**Comment by remizorrr** [comment]
Can we create a PR for the change, that @SuhaibI  have made, and merge it into the public repo? then switch to the public repo instead of our internal fork?
CC: @valeriyo

**Comment by lucasderraugh** [comment]
> Can we create a PR for the change, that @SuhaibI have made, and merge it into the public repo? then switch to the public repo instead of our internal fork?
> CC: @valeriyo

Guess that depends on if the changes he made were generic. If they are generic though to all then it would be wonderful to get off this private repo 😄

**Comment by meiyu2019** [comment]
> > Can we create a PR for the change, that @SuhaibI have made, and merge it into the public repo? then switch to the public repo instead of our internal fork?
> > CC: @valeriyo
> 
> Guess that depends on if the changes he made were generic. If they are generic though to all then it would be wonderful to get off this private repo 😄

I don't think the changes were generic enough to be approved to a public shared repo.  I will look into directly using the most updated SDK and see if we can solve the problem without modification to the SDK.

**Comment by meiyu2019** [comment]
pull all new change from upstream at once; therefore, closing this reverting of mid version.

**Pull request closed without merging**
